version: '3.1'

services:
  app:
    image: backend
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: backend
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb