version: '3.1'

services:
  app:
    image: backend
    build:
      context: .
    container_name: backend
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aktoria