version: '3.1'

services:
  app:
    image: backend
    build:
      context: .
    container_name: backend
    depends_on:
      - db

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb